#!/bin/bash
# The following code is generated by ChatGPT for workspace switching

# Define the target workspace
target_workspace=$1

# Check if the target workspace is provided
if [ -z "$target_workspace" ]; then
    echo "Usage: $0 <workspace_number>"
    exit 1
fi

# Get the current workspace
current_workspace=$(wmctrl -d | grep '*' | awk '{print $1}')

# Check if the current and target workspaces are the same
if [ "$current_workspace" == "$target_workspace" ]; then
    echo "Already on workspace $target_workspace"
    exit 0
fi

# Switch to the target workspace
wmctrl -s "$target_workspace"

echo "Switched to workspace $target_workspace"